version: '3.8'

services:

  api:
    image: r5:latest
    build:
      context: .
      dockerfile: development/Dockerfiles/Dockerfile
      target: release
    ports:
      - "8443:443"
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      R5_LOG: "DEBUG"
      R5_DRIVER: "mysql+pymysql"
      R5_DATABASE_HOSTNAME: "msql"
      R5_DATABASE_NAME: "r5"
      R5_DATABASE_USER: "user"
      R5_DATABASE_PASSWORD: "password"
      R5_SSL_KEY: "/app/key.pem"
      R5_SSL_CRT: "/app/cert.pem"
      S3_DATASETS_BUCKET_NAME: "mechanizedai-data"
    entrypoint: ["r5", "start", "--inet", "0.0.0.0", "--port", "443", "--ssl"]
    depends_on:
      - msql

networks:
  default:
    name: r5