version: '3.8'

services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: r5
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"

networks:
  default:
    name: r5